<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
      <modelVersion>4.0.0</modelVersion>
      <groupId>br.com.pedro.ebac</groupId><artifactId>entregas-java</artifactId><version>1.0.0</version><packaging>pom</packaging>
      <properties><maven.compiler.release>17</maven.compiler.release><project.build.sourceEncoding>UTF-8</project.build.sourceEncoding><project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding></properties>
      <dependencyManagement><dependencies><dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><version>5.11.4</version></dependency></dependencies></dependencyManagement>
      <build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><version>3.13.0</version></plugin><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-surefire-plugin</artifactId><version>3.5.2</version></plugin></plugins></build>
      <modules><module>mod5</module><module>mod13</module><module>mod15</module><module>mod17</module><module>mod18</module><module>mod19</module><module>mod22</module><module>mod23</module><module>java-pro/mod1</module><module>java-pro/mod2</module><module>java-pro/mod3</module><module>java-pro/mod5</module></modules>
    </project>
