spring.application.name=mod40
server.address=${SERVER_ADDRESS:127.0.0.1}
server.port=${SERVER_PORT:8080}
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never
server.error.include-message=never
server.error.include-stacktrace=never
