CREATE TABLE funcionario(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,nome VARCHAR(100) NOT NULL);
CREATE TABLE raca(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,nome VARCHAR(100) NOT NULL,especie VARCHAR(20) NOT NULL CHECK(especie IN ('CACHORRO','GATO')));
CREATE TABLE animal(id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,nome VARCHAR(100) NOT NULL,raca_id BIGINT NOT NULL REFERENCES raca(id),funcionario_id BIGINT NOT NULL REFERENCES funcionario(id),data_resgate DATE NOT NULL);
CREATE INDEX idx_animal_funcionario_data ON animal(funcionario_id,data_resgate);
